### ISSUE TITLE
before/after do they refer to processing time?

### ISSUE THREAD

**Issue by kaelumania** [ottogroup/flink-spector#31] opened 2016-11-14 15:35 UTC
Hi,

I have POJOs that describe sensor values (id, timestamp, value), thus I use a custom event time extractor and key by id with windows of 1 minutes:

```java
        DataStream<SensorValue> values =
                createTimedTestStreamWith(new SensorValue(1L, 2.0, 0L))
                        .emit(new SensorValue(1L, 12.0, 60001L), after(5, seconds))
                        .emit(new SensorValue(1L, 16.0, 60002L), after(5, seconds))
                        .emit(new SensorValue(1L, 10.0, 1L), after(2, minutes))
                        .close();

        DataStream<SensorValueAggregate> aggregates = values
                .assignTimestampsAndWatermarks(new SensorTimestampsAndWatermarks())
                .keyBy("id")
                .timeWindow(Time.minutes(1))
                .apply(new SensorValueAggregate(), new AggregateSensorValues(), new AggregateSensorValues());
```

do the `after(5, seconds)` refer to processing time? I expected to miss the last sensor value du to 1 minute windows. Does the `after(5, seconds)` have no effect as I have overwritten the timestamp extractor?

-----
*UPDATE*

I was able to achieve the element dropping using a custom watermark assigner with punctuation, where I emitted a watermark after each element. But it would be useful to define timing behavior also on processing time.

**Comment by lofifnc** [comment] 2016-11-15 09:11
Hi, 
The before and after notation will produce a StreamingSource which will emit records with timestamps and watermarks based on that description. Internally the time semantic of the streaming environment is set to EventTime. If I'm not mistaken the timestamp extractor will ignore the watermarks which flink-spector produces and attach new timestamps and watermarks.

Is the last value inserted into the first window? Or does it show up in a second window? If it is aggregated  in a second window this is the normal behavior of the tests. Based on your input it the test should produce two tumbling windows. The first one contains the first three records and the second one the last record.

The ability to work with processing time would help with testing a number of different scenarios.
But as of yet I haven't found a good way of manipulating processing time or syncing it precisely with the incoming records.

Best Regards, Alex

**Comment by lofifnc** [comment] 2016-11-15 09:44
I'm going to close this issue as it is in some way a duplicate of issue #29.

**Closed by lofifnc** 2016-11-15 09:44 UTC
