### ISSUE TITLE
Add option to use single minicluster for a group of tests to improve run time.

### ISSUE THREAD

**Issue by minaevd** [ottogroup/flink-spector#62] opened 2017-08-24 00:59 UTC
Currently a minicluster is created for every single test and it takes too long and sometimes can be unnecessary. This option can be used to improve run time of running multiple tests by setting up a single minicluster instead for all the tests in suite.

**Comment by lofifnc** [comment] 2017-08-24 08:43
This is a duplicate of #25. However as there is concrete interest in this feature, I'm going to look into this next.

**Closed** 2017-08-24 08:43 UTC
